#pragma once

enum class InstructionType : short {
    PROCEDURE_CALL,
    PARAMETER_EXPRESSION,
    OPERATION,
    ASSIGNATION,
    EXPRESSION,
    SQUARE_EXPRESSION,
    DECLARATION,
    INITIALIZATION,
    ARRAY_INIZIALIZATION,
    STRUCTURE,
    FOR_STRUCTURE,
    FOR_INITIALIZATION,
    FOR_CONDITION,
    FOR_STEP,
    DEFINITION,
    OPEN_SCOPE,
    CLOSE_SCOPE,
    BLANK
};