#pragma once

enum class InstructionType : short {
    PROCEDURE_CALL,
    PARAMETER_EXPRESSION,
    OPERATION,
    ASSIGNATION,
    EXPRESSION,
    SQUARE_EXPRESSION,
    RETURN_EXPRESSION,
    DECLARATION,
    INITIALIZATION,
    ARRAY_INIZIALIZATION,
    MAIN,
    STRUCTURE,
    FOR_STRUCTURE,
    FOR_INITIALIZATION,
    FOR_CONDITION,
    FOR_STEP,
    DEFINITION,
    PARAMETER_DEFINITION,
    RETURN_DEFINITION,
    OPEN_SCOPE,
    CLOSE_SCOPE,
    BLANK
};